# Dependencies
#markdown:         redcarpet
rouge:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            ALaSca
subtitle:         

description:      An Automated Approach for Large-Scale Lexical Substitution
# url: 
#baseurl: docs
#baseurl: https://caterinalacerra.github.io/alasca/docs

author:
  name:           'Caterina Lacerra'
  url:            https://twitter.com/CaterinaLac

paginate:         2

# Custom vars
version:          2.1.0
